### ISSUE TITLE
how can this app be build

### ISSUE THREAD

**Issue by theScrabi** [baiatBun/Chess-Clock#1]
How can one build this app?

**Comment by baiatBun** [comment]
See https://github.com/baiatBun/Instalatorul/tree/master/kivy

**Comment by theScrabi** [comment]
Hoe can it be build on android?

**Comment by baiatBun** [comment]
The link above is for building for android. Here are some builds: https://github.com/baiatBun/Chess-Clock/tree/master/bin

**Comment by theScrabi** [comment]
hm...

**Comment by baiatBun** [comment]
Did you manage to build it?

**Comment by theScrabi** [comment]
No Im sorry, I don't have time for it.
